export const CharMap = {
  UpTriangle: "▲",
  DownTriangle: "▼",
  LeftTriangle: "◀",
  RightTriangle: "▶",
  UpTriangleOutlined: "△",
  DownTriangleOutlined: "▽",
  LeftTriangleOutlined: "◁",
  RightTriangleOutlined: "▷",
  Mul: "×",
  Div: "÷",
  PlusMinus: "±",
  Plus: "+",
  Minus: "−",
  Check: "✔",
  Cross: "✘",
  Bullet: "•",
  BoldSixPointedAsterisk: "🞷",
  Refresh: "↻",
  OverlappingSquares: "⧉",
  UpArrow: "⬆",
  DownArrow: "⬇",
  LeftArrow: "⬅",
  RightArrow: "➡",
  UpDown: "↕",
  Flag: "⚑",
};
