import * as path from "node:path";
import { pathToFileURL } from "node:url";
import * as ts from "typescript";
import { ensureDir, fileExists, readTextFileAsync, writeTextFile } from "../../utils/fileSystem";
import { isLuaIdentifierName } from "../../utils/lua/lua_utils";
import { isTicbuildConstantSymbol } from "./TypeScriptConstantPlugin";

export const TYPESCRIPT_LUA_DECLARATIONS_FILE = "typescript-globals.d.lua";

export type LuaGlobalDefinitionBlock = {
  kind: "global";
  name: string;
  code: string;
};

export type LuaTypeDefinitionBlock = {
  kind: "type";
  name: string;
  code: string;
};

export type LuaDefinitionBlock = LuaGlobalDefinitionBlock | LuaTypeDefinitionBlock;

type NamedTypeDeclaration = LuaTypeDefinitionBlock;

type GlobalSymbol = {
  name: string;
  symbol: ts.Symbol;
};

export function getTypeScriptLuaDeclarationsPath(projectDir: string): string {
  return path.join(projectDir, ".ticbuild", "declarations", TYPESCRIPT_LUA_DECLARATIONS_FILE);
}


// returns a string with all whitespace collapsed to single spaces and trimmed
function singleLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function distinct(values: readonly string[]): string[] {
  return Array.from(new Set(values));
}


/**
 * Collects the Lua globals actually exposed by ticbuild's flattened TypeScript
 * linker and renders their checker types as LuaCATS definition blocks.
 */
export function collectTypeScriptLuaDefinitionBlocks(
  program: ts.Program,
  moduleSourceFiles: readonly ts.SourceFile[],
  entrySourceFile: ts.SourceFile,
  entryCallbackNames: ReadonlySet<string>,
  projectDir: string,
): LuaDefinitionBlock[] {
  const checker = program.getTypeChecker();
  const globals = new Map<string, ts.Symbol>();

  for (const sourceFile of moduleSourceFiles) {
    const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
    if (!moduleSymbol) {
      continue;
    }
    for (const exportedSymbol of checker.getExportsOfModule(moduleSymbol)) {
      if (exportedSymbol.name === "default" || exportedSymbol.name === "export=") {
        continue;
      }
      const target = resolveAliasedSymbol(checker, exportedSymbol);
      if (
        (target.flags & ts.SymbolFlags.Value) !== 0 &&
        !isTicbuildConstantSymbol(checker, target, sourceFile)// note: constant exports are compile-time literals and don't produce Lua.
      ) {
        globals.set(exportedSymbol.name, target);
      }
    }
  }

  for (const callback of findTopLevelSymbols(checker, entrySourceFile, entryCallbackNames)) {
    globals.set(callback.name, callback.symbol);
  }

  const converter = new LuaCatsTypeConverter(checker, projectDir);
  const globalBlocks = Array.from(globals, ([name, symbol]) => ({ name, symbol }))
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((global) => renderGlobalDefinition(global, converter));

  return [
    ...converter.getNamedTypeDeclarations(),
    ...globalBlocks,
  ];
}

export function renderTypeScriptLuaDeclarations(blocks: readonly LuaDefinitionBlock[]): string {
  const typesByName = new Map<string, LuaTypeDefinitionBlock>();
  const globalsByName = new Map<string, LuaGlobalDefinitionBlock>();
  for (const block of blocks) {
    switch (block.kind) {
      case "type":
        addDefinitionBlock(
          typesByName,
          block,
          `TypeScript resources emit conflicting Lua type '${block.name}'`,
        );
        break;
      case "global":
        addDefinitionBlock(
          globalsByName,
          block,
          `TypeScript resources both declare Lua global '${block.name}'`,
        );
        break;
    }
  }
  const byName = (left: LuaDefinitionBlock, right: LuaDefinitionBlock) => left.name.localeCompare(right.name);
  const ordered = [
    ...Array.from(typesByName.values()).sort(byName),
    ...Array.from(globalsByName.values()).sort(byName),
  ];
  return [
    "---@meta _",
    "-- Generated by ticbuild. Do not edit.",
    "",
    ...ordered.flatMap((block) => [block.code.trimEnd(), ""]),
  ].join("\n");
}

function addDefinitionBlock<T extends LuaDefinitionBlock>(
  byName: Map<string, T>,
  block: T,
  conflictMessage: string,
): void {
  const existing = byName.get(block.name);
  if (existing && existing.code !== block.code) {
    throw new Error(conflictMessage);
  }
  byName.set(block.name, block);
}

export async function writeTypeScriptLuaDeclarations(
  projectDir: string,
  blocks: readonly LuaDefinitionBlock[],
): Promise<void> {
  const declarationPath = getTypeScriptLuaDeclarationsPath(projectDir);
  const content = renderTypeScriptLuaDeclarations(blocks);
  if (fileExists(declarationPath) && await readTextFileAsync(declarationPath, "utf-8") === content) {
    return;
  }
  ensureDir(path.dirname(declarationPath));
  await writeTextFile(declarationPath, content, "utf-8");
}

// for re-exported symbols, resolve the alias to the actual symbol
function resolveAliasedSymbol(checker: ts.TypeChecker, symbol: ts.Symbol): ts.Symbol {
  return symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
}

function findTopLevelSymbols(
  checker: ts.TypeChecker,
  sourceFile: ts.SourceFile,
  names: ReadonlySet<string>,
): GlobalSymbol[] {
  const result: GlobalSymbol[] = [];
  const add = (name: ts.Identifier) => {
    if (!names.has(name.text)) {
      return;
    }
    const symbol = checker.getSymbolAtLocation(name);
    if (symbol) {
      result.push({ name: name.text, symbol });
    }
  };
  for (const statement of sourceFile.statements) {
    if (ts.isFunctionDeclaration(statement) && statement.name) {
      add(statement.name);
      continue;
    }
    if (ts.isVariableStatement(statement)) {
      for (const declaration of statement.declarationList.declarations) {
        if (ts.isIdentifier(declaration.name)) {
          add(declaration.name);
        }
      }
    }
  }
  return result;
}


function renderGlobalDefinition(global: GlobalSymbol, converter: LuaCatsTypeConverter): LuaGlobalDefinitionBlock {
  const declaration = preferredDeclaration(global.symbol);
  const type = declaration
    ? converter.checker.getTypeOfSymbolAtLocation(global.symbol, declaration)
    : converter.checker.getTypeOfSymbol(global.symbol);
  const signatures = converter.checker.getSignaturesOfType(type, ts.SignatureKind.Call);
  const lines: string[] = [];
  appendDescription(lines, documentationText(global.symbol, converter.checker));
  appendDeprecated(lines, global.symbol, converter.checker);
  appendSource(lines, declaration);

  if (signatures.length > 0) {
    const primary = signatures[0];
    for (const parameter of renderSignatureParameters(primary, converter, true)) {
      lines.push(`---@param ${parameter.name}${parameter.optional ? "?" : ""} ${parameter.type}${parameter.description ? ` ${singleLine(parameter.description)}` : ""
        }`);
    }
    const returnInfo = renderSignatureReturns(primary, converter);
    for (const [index, returnType] of returnInfo.types.entries()) {
      const description = index === 0 ? returnInfo.description : undefined;
      lines.push(`---@return ${returnType}${description ? ` # ${singleLine(description)}` : ""}`);
    }
    for (const overload of signatures.slice(1)) {
      lines.push(`---@overload ${converter.signatureToFunctionType(overload)}`);
    }
    const parameters = renderSignatureParameters(primary, converter, false).map((parameter) => parameter.name);
    lines.push(`function ${global.name}(${parameters.join(", ")}) end`);
  } else {
    lines.push(`---@type ${converter.typeToLua(type)}`);
    lines.push(`${global.name} = nil`);
  }

  return { kind: "global", name: global.name, code: lines.join("\n") };
}

type RenderedParameter = {
  name: string;
  type: string;
  optional: boolean;
  description?: string;
};

function renderSignatureParameters(
  signature: ts.Signature,
  converter: LuaCatsTypeConverter,
  includeDescriptions: boolean,
): RenderedParameter[] {
  return signature.getParameters().map((parameter, index) => {
    const declaration = preferredDeclaration(parameter) ?? signature.getDeclaration();
    let parameterType = declaration
      ? converter.checker.getTypeOfSymbolAtLocation(parameter, declaration)
      : converter.checker.getTypeOfSymbol(parameter);
    const parameterDeclaration = parameter.valueDeclaration && ts.isParameter(parameter.valueDeclaration)
      ? parameter.valueDeclaration
      : undefined;
    const isRest = parameterDeclaration?.dotDotDotToken !== undefined;
    if (isRest && converter.checker.isArrayType(parameterType)) {
      parameterType = converter.checker.getTypeArguments(parameterType as ts.TypeReference)[0] ?? parameterType;
    }
    const rawName = isRest ? "..." : parameter.name;
    const optional = !isRest && (
      (parameter.flags & ts.SymbolFlags.Optional) !== 0 ||
      parameterDeclaration?.questionToken !== undefined ||
      parameterDeclaration?.initializer !== undefined
    );
    return {
      name: rawName === "..." ? rawName : sanitizeLuaIdentifier(rawName, `arg${index + 1}`),
      type: optional ? converter.typeToLuaWithoutNil(parameterType) : converter.typeToLua(parameterType),
      optional,
      description: includeDescriptions ? documentationText(parameter, converter.checker) : undefined,
    };
  });
}

function renderSignatureReturns(
  signature: ts.Signature,
  converter: LuaCatsTypeConverter,
): { types: string[]; description?: string } {
  const returnType = converter.checker.getReturnTypeOfSignature(signature);
  if (isOnlyVoidLike(returnType)) {
    return { types: [] };
  }
  return {
    types: converter.returnTypesToLua(returnType),
    description: jsDocReturnText(signature.getDeclaration()),
  };
}

class LuaCatsTypeConverter {
  readonly namedTypes = new Map<ts.Symbol, NamedTypeDeclaration>();

  constructor(
    readonly checker: ts.TypeChecker,
    private readonly projectDir: string,
  ) { }

  getNamedTypeDeclarations(): NamedTypeDeclaration[] {
    return Array.from(this.namedTypes.values()).sort((left, right) => left.name.localeCompare(right.name));
  }

  typeToLua(type: ts.Type, depth = 0, skipNamedSymbol?: ts.Symbol): string {
    if (depth > 12) {
      return "any";
    }

    const namedSymbol = this.getProjectNamedTypeSymbol(type);
    if (namedSymbol && namedSymbol !== skipNamedSymbol) {
      const named = this.ensureNamedType(namedSymbol, type, depth + 1);
      if (named) {
        return named;
      }
    }

    if (type.isUnion()) {
      return normalizeLuaUnion(type.types.map((part) => this.typeToLua(part, depth + 1)));
    }
    if (type.isIntersection()) {
      return this.renderObjectType(type, depth + 1);
    }
    if (type.flags & (ts.TypeFlags.Any | ts.TypeFlags.Unknown)) {
      return "any";
    }
    if (type.flags & ts.TypeFlags.Never) {
      return "nil";
    }
    if (type.flags & (ts.TypeFlags.Void | ts.TypeFlags.Undefined | ts.TypeFlags.Null)) {
      return "nil";
    }
    if (type.flags & ts.TypeFlags.BooleanLike) {
      if (type.flags & ts.TypeFlags.BooleanLiteral) {
        return this.checker.typeToString(type) === "true" ? "true" : "false";
      }
      return "boolean";
    }
    if (type.flags & ts.TypeFlags.StringLiteral) {
      return JSON.stringify((type as ts.StringLiteralType).value);
    }
    if (type.flags & ts.TypeFlags.StringLike) {
      return "string";
    }
    if (type.flags & ts.TypeFlags.NumberLiteral) {
      return String((type as ts.NumberLiteralType).value);
    }
    if (type.flags & ts.TypeFlags.NumberLike) {
      return "number";
    }
    if (type.flags & ts.TypeFlags.BigIntLike) {
      return "integer";
    }
    if (type.flags & ts.TypeFlags.TypeParameter) {
      return "any";
    }

    if (this.checker.isTupleType(type)) {
      const members = this.checker.getTypeArguments(type as ts.TypeReference)
        .map((member) => this.typeToLua(member, depth + 1));
      return `[${members.join(", ")}]`;
    }
    if (this.checker.isArrayType(type)) {
      const member = this.checker.getTypeArguments(type as ts.TypeReference)[0];
      const rendered = member ? this.typeToLua(member, depth + 1) : "any";
      return `${rendered.includes("|") ? `(${rendered})` : rendered}[]`;
    }

    const callSignatures = this.checker.getSignaturesOfType(type, ts.SignatureKind.Call);
    if (callSignatures.length > 0) {
      return this.signatureToFunctionType(callSignatures[0], depth + 1);
    }
    if (this.checker.getSignaturesOfType(type, ts.SignatureKind.Construct).length > 0) {
      return "table";
    }
    if (type.flags & ts.TypeFlags.Object) {
      return this.renderObjectType(type, depth + 1);
    }
    return "any";
  }

  typeToLuaWithoutNil(type: ts.Type, depth = 0): string {
    if (!type.isUnion()) {
      return this.typeToLua(type, depth);
    }
    const nonNil = type.types.filter((part) => !isOnlyNilLike(part));
    return nonNil.length > 0
      ? normalizeLuaUnion(nonNil.map((part) => this.typeToLua(part, depth + 1)))
      : "nil";
  }

  returnTypesToLua(type: ts.Type, depth = 0): string[] {
    const multiReturn = getLuaMultiReturnMembers(type, this.checker);
    return multiReturn
      ? multiReturn.map((member) => this.typeToLua(member, depth + 1))
      : [this.typeToLua(type, depth)];
  }

  signatureToFunctionType(signature: ts.Signature, depth = 0, selfType?: string): string {
    const parameters = renderSignatureParameters(signature, this, false)
      .map((parameter) => `${parameter.name}${parameter.optional ? "?" : ""}: ${parameter.type}`);
    if (selfType) {
      parameters.unshift(`self: ${selfType}`);
    }
    const returnType = this.checker.getReturnTypeOfSignature(signature);
    const renderedReturn = isOnlyVoidLike(returnType)
      ? ""
      : `: ${this.returnTypesToLua(returnType, depth + 1).join(", ")}`;
    return `fun(${parameters.join(", ")})${renderedReturn}`;
  }

  private renderObjectType(type: ts.Type, depth: number): string {
    const stringIndex = this.checker.getIndexTypeOfType(type, ts.IndexKind.String);
    if (stringIndex) {
      return `table<string, ${this.typeToLua(stringIndex, depth + 1)}>`;
    }
    const numberIndex = this.checker.getIndexTypeOfType(type, ts.IndexKind.Number);
    if (numberIndex) {
      return `table<number, ${this.typeToLua(numberIndex, depth + 1)}>`;
    }
    const properties = this.checker.getPropertiesOfType(type);
    if (properties.length === 0 || properties.length > 24) {
      return "table";
    }
    const fields = properties.map((property) => {
      const declaration = preferredDeclaration(property);
      const propertyType = declaration
        ? this.checker.getTypeOfSymbolAtLocation(property, declaration)
        : this.checker.getTypeOfSymbol(property);
      const name = renderLuaCatsFieldName(property.name);
      const isOptional = (property.flags & ts.SymbolFlags.Optional) !== 0;
      const optional = isOptional ? "?" : "";
      const signatures = this.checker.getSignaturesOfType(propertyType, ts.SignatureKind.Call);
      const renderedType = signatures.length > 0 && isSelfMethodDeclaration(declaration)
        ? this.signatureToFunctionType(signatures[0], depth + 1, "table")
        : isOptional
          ? this.typeToLuaWithoutNil(propertyType, depth + 1)
          : this.typeToLua(propertyType, depth + 1);
      return `${name}${optional}: ${renderedType}`;
    });
    return `{ ${fields.join(", ")} }`;
  }

  private getProjectNamedTypeSymbol(type: ts.Type): ts.Symbol | undefined {
    const symbol = type.aliasSymbol ?? type.getSymbol();
    if (!symbol) {
      return undefined;
    }
    const declaration = symbol.declarations?.find((candidate) =>
      ts.isTypeAliasDeclaration(candidate) ||
      ts.isInterfaceDeclaration(candidate) ||
      ts.isClassDeclaration(candidate) ||
      ts.isEnumDeclaration(candidate),
    );
    if (!declaration || hasTypeParameters(declaration)) {
      return undefined;
    }
    const relative = path.relative(this.projectDir, declaration.getSourceFile().fileName);
    if (relative.startsWith("..") || path.isAbsolute(relative)) {
      return undefined;
    }
    if (ts.isClassDeclaration(declaration) && this.checker.getSignaturesOfType(type, ts.SignatureKind.Construct).length > 0) {
      return undefined;
    }
    if (ts.isEnumDeclaration(declaration) && type.flags & ts.TypeFlags.Object) {
      return undefined;
    }
    return symbol;
  }

  private ensureNamedType(symbol: ts.Symbol, type: ts.Type, depth: number): string | undefined {
    const existing = this.namedTypes.get(symbol);
    if (existing) {
      return existing.name;
    }
    const declaration = symbol.declarations?.find((candidate) =>
      ts.isTypeAliasDeclaration(candidate) ||
      ts.isInterfaceDeclaration(candidate) ||
      ts.isClassDeclaration(candidate) ||
      ts.isEnumDeclaration(candidate),
    );
    if (!declaration) {
      return undefined;
    }
    const typeName = makeLuaCatsTypeName(this.projectDir, declaration.getSourceFile(), symbol.name);
    this.namedTypes.set(symbol, { kind: "type", name: typeName, code: "" });

    const lines: string[] = [];
    appendDescription(lines, documentationText(symbol, this.checker));
    appendSource(lines, declaration);
    if (ts.isTypeAliasDeclaration(declaration) || ts.isEnumDeclaration(declaration)) {
      const declaredType = this.checker.getDeclaredTypeOfSymbol(symbol);
      lines.push(`---@alias ${typeName} ${this.typeToLua(declaredType, depth + 1, symbol)}`);
    } else {
      lines.push(`---@class ${typeName}`);
      const declaredType = this.checker.getDeclaredTypeOfSymbol(symbol);
      for (const property of this.checker.getPropertiesOfType(declaredType)) {
        const propertyDeclaration = preferredDeclaration(property);
        const propertyType = propertyDeclaration
          ? this.checker.getTypeOfSymbolAtLocation(property, propertyDeclaration)
          : this.checker.getTypeOfSymbol(property);
        let renderedType: string;
        const signatures = this.checker.getSignaturesOfType(propertyType, ts.SignatureKind.Call);
        if (signatures.length > 0 && isSelfMethodDeclaration(propertyDeclaration)) {
          renderedType = this.signatureToFunctionType(signatures[0], depth + 1, typeName);
        } else {
          renderedType = this.typeToLua(propertyType, depth + 1);
        }
        const isOptional = (property.flags & ts.SymbolFlags.Optional) !== 0;
        const optional = isOptional ? "?" : "";
        const description = documentationText(property, this.checker);
        if (isOptional && signatures.length === 0) {
          renderedType = this.typeToLuaWithoutNil(propertyType, depth + 1);
        }
        lines.push(`---@field ${renderLuaCatsFieldName(property.name)}${optional} ${renderedType}${description ? ` ${singleLine(description)}` : ""
          }`);
      }
      lines.push(`local __ticbuild_type_${sanitizeTypePlaceholder(typeName)} = {}`);
    }
    this.namedTypes.set(symbol, { kind: "type", name: typeName, code: lines.join("\n") });
    return typeName;
  }
}

function preferredDeclaration(symbol: ts.Symbol): ts.Declaration | undefined {
  return symbol.valueDeclaration ?? symbol.declarations?.[0];
}

function documentationText(symbol: ts.Symbol, checker: ts.TypeChecker): string | undefined {
  const text = ts.displayPartsToString(symbol.getDocumentationComment(checker)).trim();
  return text || undefined;
}

function appendDescription(lines: string[], description: string | undefined): void {
  if (!description) {
    return;
  }
  for (const line of description.split(/\r?\n/)) {
    lines.push(line.trim() ? `--- ${line.trim()}` : "---");
  }
}

function appendDeprecated(lines: string[], symbol: ts.Symbol, checker: ts.TypeChecker): void {
  const tag = symbol.getJsDocTags(checker).find((candidate) => candidate.name === "deprecated");
  if (!tag) {
    return;
  }
  const message = tag.text ? ts.displayPartsToString(tag.text).trim() : "";
  lines.push(`---@deprecated${message ? ` ${singleLine(message)}` : ""}`);
}

function appendSource(lines: string[], declaration: ts.Declaration | undefined): void {
  if (!declaration) {
    return;
  }
  const sourceFile = declaration.getSourceFile();
  const location = sourceFile.getLineAndCharacterOfPosition(declaration.getStart(sourceFile));
  lines.push(`---@source ${pathToFileURL(sourceFile.fileName).href}:${location.line + 1}:${location.character + 1}`);
}

function jsDocReturnText(declaration: ts.SignatureDeclaration | undefined): string | undefined {
  if (!declaration) {
    return undefined;
  }
  const tag = ts.getJSDocReturnTag(declaration);
  if (!tag?.comment) {
    return undefined;
  }
  if (typeof tag.comment === "string") {
    return tag.comment.trim() || undefined;
  }
  const text = tag.comment.map((part) => part.text).join("").trim();
  return text || undefined;
}

function makeLuaCatsTypeName(projectDir: string, sourceFile: ts.SourceFile, symbolName: string): string {
  const relative = path.relative(projectDir, sourceFile.fileName).replace(/\.[^.\\/]+$/, "");
  const pathParts = relative.split(/[\\/]+/).map((part) => sanitizeTypeNamePart(part)).filter(Boolean);
  return ["ticbuild", ...pathParts, sanitizeTypeNamePart(symbolName)].join(".");
}

function sanitizeTypeNamePart(value: string): string {
  const sanitized = value.replace(/[^A-Za-z0-9_]/g, "_");
  if (!sanitized) {
    return "_";
  }
  return /^[A-Za-z_]/.test(sanitized) ? sanitized : `_${sanitized}`;
}

function sanitizeTypePlaceholder(value: string): string {
  return value.replace(/[^A-Za-z0-9_]/g, "_");
}

function sanitizeLuaIdentifier(value: string, fallback: string): string {
  return isLuaIdentifierName(value) ? value : fallback;
}

function renderLuaCatsFieldName(name: string): string {
  return isLuaIdentifierName(name) ? name : `[${JSON.stringify(name)}]`;
}

function hasTypeParameters(
  declaration: ts.TypeAliasDeclaration | ts.InterfaceDeclaration | ts.ClassDeclaration | ts.EnumDeclaration,
): boolean {
  return !ts.isEnumDeclaration(declaration) && (declaration.typeParameters?.length ?? 0) > 0;
}

function isSelfMethodDeclaration(declaration: ts.Declaration | undefined): boolean {
  return declaration !== undefined && (
    ts.isMethodDeclaration(declaration) ||
    ts.isMethodSignature(declaration)
  );
}

// checks if a type is only void, undefined, or never
// (has no other possible values)
function isOnlyVoidLike(type: ts.Type): boolean {
  if (type.isUnion()) {
    return type.types.every(isOnlyVoidLike);
  }
  return (type.flags & (ts.TypeFlags.Void | ts.TypeFlags.Undefined | ts.TypeFlags.Never)) !== 0;
}

function isOnlyNilLike(type: ts.Type): boolean {
  return (type.flags & (ts.TypeFlags.Void | ts.TypeFlags.Undefined | ts.TypeFlags.Null)) !== 0;
}

function normalizeLuaUnion(parts: readonly string[]): string {
  const normalized = distinct(parts);
  const trueIndex = normalized.indexOf("true");
  const falseIndex = normalized.indexOf("false");
  if (trueIndex >= 0 && falseIndex >= 0) {
    normalized.splice(Math.max(trueIndex, falseIndex), 1);
    normalized.splice(Math.min(trueIndex, falseIndex), 1, "boolean");
  }
  const nilIndex = normalized.indexOf("nil");
  if (nilIndex >= 0 && nilIndex !== normalized.length - 1) {
    normalized.splice(nilIndex, 1);
    normalized.push("nil");
  }
  return normalized.join("|") || "any";
}

function getLuaMultiReturnMembers(type: ts.Type, checker: ts.TypeChecker): readonly ts.Type[] | undefined {
  if (type.aliasSymbol?.name !== "LuaMultiReturn" || !type.aliasTypeArguments?.[0]) {
    return undefined;
  }
  const tuple = type.aliasTypeArguments[0];
  return checker.isTupleType(tuple) ? checker.getTypeArguments(tuple as ts.TypeReference) : undefined;
}
