import * as path from "node:path";
import { ensureDir, fileExists, readTextFileAsync, writeTextFile } from "../../utils/fileSystem";
import { PreprocessorValue } from "../manifestTypes";
import { getResolvedPreprocessorDefines } from "../preprocessorDefines";
import { TicbuildProjectCore } from "../projectCore";

export const TYPESCRIPT_BUILD_CONSTANTS_FILE = "build-constants.d.ts";

export function getTypeScriptBuildConstantsPath(projectDir: string): string {
  return path.join(projectDir, ".ticbuild", "declarations", TYPESCRIPT_BUILD_CONSTANTS_FILE);
}

function renderLiteral(value: PreprocessorValue): string {
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}

export function renderTypeScriptBuildConstants(project: TicbuildProjectCore): string {
  const defineProperties = Object.entries(getResolvedPreprocessorDefines(project))
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, value]) => `    readonly ${JSON.stringify(name)}: ${renderLiteral(value)};`);
  const variableProperties = Array.from(project.allVariables.values())
    .sort((left, right) => left.name.localeCompare(right.name))
    .map(({ name, resolvedValue }) => `    readonly ${JSON.stringify(name)}: ${renderLiteral(resolvedValue)};`);

  return [
    "// Generated by ticbuild. Changes will be overwritten.",
    "declare namespace ticbuild {",
    "  interface Defines {",
    ...defineProperties,
    "  }",
    "  interface Vars {",
    ...variableProperties,
    "  }",
    "}",
    "",
  ].join("\n");
}

export async function writeTypeScriptBuildConstants(project: TicbuildProjectCore): Promise<void> {
  const declarationPath = getTypeScriptBuildConstantsPath(project.projectDir);
  const content = renderTypeScriptBuildConstants(project);
  if (fileExists(declarationPath) && await readTextFileAsync(declarationPath, "utf-8") === content) {
    return;
  }
  ensureDir(path.dirname(declarationPath));
  await writeTextFile(declarationPath, content, "utf-8");
}
