// stuff for generating .ticbuild/declarations/typescript-assets.d.ts
// from typescript modules in the manifest
import * as path from "node:path";
import * as ts from "typescript";
import * as tstl from "typescript-to-lua";
import { ensureDir, fileExists, readTextFileAsync, writeTextFile } from "../../utils/fileSystem";
import { TypeScriptImportConfig } from "../manifestTypes";
import { TicbuildProjectCore } from "../projectCore";
import {
  createManifestCodeModuleCatalog,
  MANIFEST_CODE_MODULE_PREFIX,
  ManifestCodeModuleDefinition,
  parseManifestCodeModuleSpecifier,
} from "./ManifestCodeTypeScriptModules";
import { createTypeScriptTranspilationOptions } from "./TypeScriptTranspilationOptions";
import { loadTypeScriptProjectConfig } from "./tsconfigUtils";

export const TYPESCRIPT_MANIFEST_DECLARATIONS_FILE = "typescript-assets.d.ts";

export type TypeScriptManifestModuleDeclaration = {
  importName: string;
  code: string;
};

type DeclarationEmitResult = {
  declaration?: TypeScriptManifestModuleDeclaration;
  diagnostics: readonly ts.Diagnostic[];
};

type EmittedDeclaration = {
  text: string;
  sourceFile: ts.SourceFile;
};

export function getTypeScriptManifestDeclarationsPath(projectDir: string): string {
  return path.join(projectDir, ".ticbuild", "declarations", TYPESCRIPT_MANIFEST_DECLARATIONS_FILE);
}

function canonicalTypeScriptPath(fileName: string): string {
  const normalized = path.normalize(path.resolve(fileName));
  return ts.sys.useCaseSensitiveFileNames ? normalized : normalized.toLowerCase();
}

// todo: unify all these. search for ".tsx" to see what i mean.
function isTypeScriptImplementationFile(fileName: string): boolean {
  const lower = fileName.toLowerCase();
  return (lower.endsWith(".ts") || lower.endsWith(".tsx")) && !lower.endsWith(".d.ts");
}

// todo: unify all these. search for ".tsx" to see what i mean.
function isTypeScriptSourceFile(fileName: string): boolean {
  const lower = fileName.toLowerCase();
  return lower.endsWith(".ts") || lower.endsWith(".tsx");
}

// todo: unify all these. search for ".tsx" to see what i mean.
function scriptKind(fileName: string): ts.ScriptKind {
  return fileName.toLowerCase().endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS;
}

export function renderTypeScriptManifestDeclarations(
  declarations: readonly TypeScriptManifestModuleDeclaration[],
): string {
  const byImportName = new Map<string, TypeScriptManifestModuleDeclaration>();
  for (const declaration of declarations) {
    const existing = byImportName.get(declaration.importName);
    if (existing && existing.code !== declaration.code) {
      throw new Error(`Conflicting TypeScript declarations for manifest import '${declaration.importName}'`);
    }
    byImportName.set(declaration.importName, declaration);
  }
  const blocks = Array.from(byImportName.values())
    .sort((left, right) => left.importName.localeCompare(right.importName))
    .map((declaration) => declaration.code.trimEnd());
  return [
    "// Generated by ticbuild. Changes will be overwritten.",
    "/** @noSelfInFile */",
    "",
    ...blocks.flatMap((block) => [block, ""]),
  ].join("\n");
}

export async function writeTypeScriptManifestDeclarations(
  projectDir: string,
  declarations: readonly TypeScriptManifestModuleDeclaration[],
): Promise<void> {
  const declarationPath = getTypeScriptManifestDeclarationsPath(projectDir);
  const content = renderTypeScriptManifestDeclarations(declarations);
  if (fileExists(declarationPath) && await readTextFileAsync(declarationPath, "utf-8") === content) {
    return;
  }
  ensureDir(path.dirname(declarationPath));
  await writeTextFile(declarationPath, content, "utf-8");
}

/**
 * Finds manifest-backed TypeScript module edges without requiring their generated
 * declarations to exist yet. Ordinary TypeScript modules are followed with the
 * importing resource's compiler options so special imports in relative/path-mapped
 * dependencies participate in resource ordering too.
 */
export function collectTypeScriptManifestDependencies(
  project: TicbuildProjectCore,
  entryFilePath: string,
  entrySource: string,
  typescriptConfig?: TypeScriptImportConfig,
): string[] {
  return collectTypeScriptManifestCodeDependencies(project, entryFilePath, entrySource, typescriptConfig)
    .filter((dependency) => dependency.kind === "TypeScriptCode")
    .map((dependency) => dependency.importName);
}

export function collectTypeScriptManifestCodeDependencies(
  project: TicbuildProjectCore,
  entryFilePath: string,
  entrySource: string,
  typescriptConfig?: TypeScriptImportConfig,
): ManifestCodeModuleDefinition[] {
  const configuredProject = loadTypeScriptProjectConfig(project, typescriptConfig);
  const options = createTypeScriptTranspilationOptions(configuredProject.options);
  const catalog = createManifestCodeModuleCatalog(project);
  const dependencies = new Map<string, ManifestCodeModuleDefinition>();
  const visited = new Set<string>();
  const entryKey = canonicalTypeScriptPath(entryFilePath);

  const visitFile = (fileName: string) => {
    const key = canonicalTypeScriptPath(fileName);
    if (visited.has(key)) {
      return;
    }
    visited.add(key);
    const sourceText = key === entryKey ? entrySource : ts.sys.readFile(fileName);
    if (sourceText === undefined) {
      return;
    }
    const sourceFile = ts.createSourceFile(fileName, sourceText, ts.ScriptTarget.Latest, true, scriptKind(fileName));

    const inspectModuleSpecifier = (moduleSpecifier: ts.Expression) => {
      if (!ts.isStringLiteralLike(moduleSpecifier)) {
        return;
      }
      const specifier = moduleSpecifier.text;
      if (specifier.startsWith(MANIFEST_CODE_MODULE_PREFIX)) {
        const importName = parseManifestCodeModuleSpecifier(specifier);
        if (!importName) {
          // The static linker reports the source-located validation error.
          return;
        }
        const definition = catalog.get(importName);
        if (!definition) {
          // The static linker reports the source-located validation error.
          return;
        }
        dependencies.set(importName, definition);
        return;
      }

      const resolved = ts.resolveModuleName(specifier, fileName, options, ts.sys).resolvedModule;
      if (resolved && isTypeScriptSourceFile(resolved.resolvedFileName)) {
        visitFile(resolved.resolvedFileName);
      }
    };

    const inspect = (node: ts.Node) => {
      if (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) {
        if (node.moduleSpecifier) {
          inspectModuleSpecifier(node.moduleSpecifier);
        }
        return;
      }
      if (
        ts.isImportTypeNode(node) &&
        ts.isLiteralTypeNode(node.argument) &&
        ts.isStringLiteralLike(node.argument.literal)
      ) {
        inspectModuleSpecifier(node.argument.literal);
        return;
      }
      ts.forEachChild(node, inspect);
    };
    ts.forEachChild(sourceFile, inspect);
  };

  visitFile(entryFilePath);
  const generatedDeclarationsDir = path.join(project.projectDir, ".ticbuild", "declarations");
  for (const declarationRootPath of configuredProject.declarationRootPaths) {
    const relativeToGeneratedDeclarations = path.relative(generatedDeclarationsDir, declarationRootPath);
    if (
      relativeToGeneratedDeclarations === "" ||
      (!relativeToGeneratedDeclarations.startsWith("..") && !path.isAbsolute(relativeToGeneratedDeclarations))
    ) {
      // Generated aggregate declarations describe work from a previous or
      // partially completed build; they are outputs, not graph-discovery roots.
      continue;
    }
    visitFile(declarationRootPath);
  }
  return Array.from(dependencies.values()).sort((left, right) => left.importName.localeCompare(right.importName));
}

export function emitTypeScriptManifestModuleDeclaration(
  program: ts.Program,
  compilerHost: ts.CompilerHost,
  entryFilePath: string,
  importName: string,
  projectDir: string,
): DeclarationEmitResult {
  const declarationOptions: tstl.CompilerOptions = {
    ...program.getCompilerOptions(),
    declaration: true,
    declarationMap: false,
    emitDeclarationOnly: true,
    inlineSourceMap: false,
    inlineSources: false,
    noEmit: false,
    noEmitOnError: false,
    outDir: undefined,
    declarationDir: undefined,
    sourceMap: false,
  };
  const declarationProgram = ts.createProgram({
    rootNames: program.getRootFileNames(),
    options: declarationOptions,
    host: compilerHost,
    oldProgram: program,
  });
  const emitted: EmittedDeclaration[] = [];
  const result = declarationProgram.emit(
    undefined,
    (fileName, text, _writeByteOrderMark, _onError, sourceFiles) => {
      if (!fileName.toLowerCase().endsWith(".d.ts")) {
        return;
      }
      const sourceFile = sourceFiles?.find((candidate) => isTypeScriptImplementationFile(candidate.fileName));
      if (sourceFile) {
        emitted.push({ text, sourceFile });
      }
    },
    undefined,
    true,
  );
  if (result.emitSkipped || emitted.length === 0) {
    return { diagnostics: result.diagnostics };
  }

  const moduleSpecifier = `${MANIFEST_CODE_MODULE_PREFIX}${importName}`;
  const moduleNames = makeVirtualModuleNames(emitted, entryFilePath, moduleSpecifier, projectDir);
  const blocks = emitted
    .sort((left, right) => {
      const leftName = moduleNames.get(canonicalTypeScriptPath(left.sourceFile.fileName)) ?? "";
      const rightName = moduleNames.get(canonicalTypeScriptPath(right.sourceFile.fileName)) ?? "";
      return leftName.localeCompare(rightName);
    })
    .map((declaration) => renderAmbientModule(declaration, moduleNames, declarationOptions, compilerHost));
  return {
    declaration: {
      importName,
      code: blocks.join("\n\n"),
    },
    diagnostics: result.diagnostics,
  };
}

function makeVirtualModuleNames(
  declarations: readonly EmittedDeclaration[],
  entryFilePath: string,
  moduleSpecifier: string,
  projectDir: string,
): ReadonlyMap<string, string> {
  const names = new Map<string, string>();
  const owners = new Map<string, string>();
  const entryKey = canonicalTypeScriptPath(entryFilePath);
  for (const declaration of declarations) {
    const key = canonicalTypeScriptPath(declaration.sourceFile.fileName);
    let name: string;
    if (key === entryKey) {
      name = moduleSpecifier;
    } else {
      const relative = path.relative(projectDir, declaration.sourceFile.fileName).replace(/\\/g, "/");
      const withoutExtension = relative.replace(/\.(?:d\.)?[cm]?tsx?$/i, "");
      const encoded = withoutExtension.split("/").map((part) => {
        if (!part || part === ".") {
          return "_";
        }
        return part === ".." ? "__up" : encodeURIComponent(part);
      }).join("/");
      name = `${moduleSpecifier}/__types/${encoded}`;
    }
    const existingOwner = owners.get(name);
    if (existingOwner && existingOwner !== key) {
      throw new Error(
        `TypeScript declaration module '${name}' is emitted by both ${existingOwner} and ${declaration.sourceFile.fileName}`,
      );
    }
    owners.set(name, key);
    names.set(key, name);
  }
  return names;
}

function renderAmbientModule(
  declaration: EmittedDeclaration,
  moduleNames: ReadonlyMap<string, string>,
  options: ts.CompilerOptions,
  compilerHost: ts.CompilerHost,
): string {
  const sourceKey = canonicalTypeScriptPath(declaration.sourceFile.fileName);
  const moduleName = moduleNames.get(sourceKey);
  if (!moduleName) {
    throw new Error(`Unable to name emitted TypeScript declaration for ${declaration.sourceFile.fileName}`);
  }
  const emittedSource = ts.createSourceFile(
    `${declaration.sourceFile.fileName}.d.ts`,
    declaration.text,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const transformed = ts.transform(emittedSource, [rewriteDeclarationModuleSpecifiers(
    declaration.sourceFile,
    moduleNames,
    options,
    compilerHost,
  )]);
  try {
    const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
    const body = printer.printFile(transformed.transformed[0] as ts.SourceFile)
      .replace(/^(\s*(?:export\s+)?)declare\s+/gm, "$1")
      .trimEnd();
    return [
      `declare module ${JSON.stringify(moduleName)} {`,
      ...body.split(/\r?\n/).map((line) => `  ${line}`),
      "}",
    ].join("\n");
  } finally {
    transformed.dispose();
  }
}

function rewriteDeclarationModuleSpecifiers(
  originalSourceFile: ts.SourceFile,
  moduleNames: ReadonlyMap<string, string>,
  options: ts.CompilerOptions,
  compilerHost: ts.CompilerHost,
): ts.TransformerFactory<ts.SourceFile> {
  return (context) => {
    const rewrite = (literal: ts.StringLiteralLike): ts.StringLiteralLike => {
      const resolved = ts.resolveModuleName(
        literal.text,
        originalSourceFile.fileName,
        options,
        compilerHost,
      ).resolvedModule;
      if (!resolved) {
        return literal;
      }
      const virtualName = moduleNames.get(canonicalTypeScriptPath(resolved.resolvedFileName));
      return virtualName ? ts.factory.createStringLiteral(virtualName) : literal;
    };
    const visit: ts.Visitor = (node) => {
      if (ts.isImportDeclaration(node) && ts.isStringLiteralLike(node.moduleSpecifier)) {
        return ts.factory.updateImportDeclaration(
          node,
          node.modifiers,
          node.importClause,
          rewrite(node.moduleSpecifier),
          node.attributes,
        );
      }
      if (ts.isExportDeclaration(node) && node.moduleSpecifier && ts.isStringLiteralLike(node.moduleSpecifier)) {
        return ts.factory.updateExportDeclaration(
          node,
          node.modifiers,
          node.isTypeOnly,
          node.exportClause,
          rewrite(node.moduleSpecifier),
          node.attributes,
        );
      }
      if (
        ts.isImportTypeNode(node) &&
        ts.isLiteralTypeNode(node.argument) &&
        ts.isStringLiteralLike(node.argument.literal)
      ) {
        return ts.factory.updateImportTypeNode(
          node,
          ts.factory.updateLiteralTypeNode(node.argument, rewrite(node.argument.literal)),
          node.attributes,
          node.qualifier,
          node.typeArguments,
          node.isTypeOf,
        );
      }
      return ts.visitEachChild(node, visit, context);
    };
    return (sourceFile) => ts.visitNode(sourceFile, visit) as ts.SourceFile;
  };
}
