import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { pathToFileURL } from "node:url";
import * as cons from "../../utils/console";
import { parseLua } from "../../utils/lua/lua_processor";
import { ResourceManager } from "../ImportedResourceTypes";
import { loadAllImports } from "../importResources";
import { Manifest } from "../manifestTypes";
import { TicbuildProjectCore } from "../projectCore";
import { mapPreprocessedOffsetToLineColumn } from "../sourceMap";
import { LuaCodeResource } from "./LuaCodeImporter";
import { TypeScriptCodeResource } from "./TypeScriptCodeImporter";
import { getLuaAssetDeclarationsPath } from "./LuaAssetTypeScriptModules";
import { getTypeScriptLuaDeclarationsPath } from "./TypeScriptLuaDeclarations";
import { getTypeScriptManifestDeclarationsPath } from "./TypeScriptManifestModules";

function createProject(projectDir: string, imports: Manifest["imports"], defines?: Record<string, boolean>) {
  const manifest: Manifest = {
    buildConfiguration: "release",
    project: {
      name: "typescript-test",
      binDir: "./bin",
      objDir: "./obj",
      outputCartName: "test.tic",
    },
    preprocessor: defines ? { defines } : undefined,
    variables: { "project.name": "typescript-test" },
    imports,
    assembly: { blocks: [{ asset: imports[0].name }] },
  };
  return new TicbuildProjectCore({
    manifest,
    manifestPath: path.join(projectDir, "manifest.ticbuild.jsonc"),
    projectDir,
  });
}

function getTypeScriptResource(resources: ResourceManager, name: string): TypeScriptCodeResource {
  const resource = resources.items.get(name);
  expect(resource).toBeInstanceOf(TypeScriptCodeResource);
  return resource as TypeScriptCodeResource;
}

describe("TypeScriptCodeResource", () => {
  it("emits LuaCATS definitions for TypeScript globals with checker types, docs, and source links", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-lua-definitions-"));
    const mainPath = path.join(projectDir, "main.ts");
    const mathPath = path.join(projectDir, "math.ts");
    fs.writeFileSync(
      mathPath,
      [
        "/** A two-dimensional vector. */",
        "export interface Vec2 {",
        "  /** Horizontal coordinate. */",
        "  x: number;",
        "  y: number;",
        "}",
        "export type Mode = \"fast\" | \"safe\";",
        "export const DEFAULT_SCALE = 2 as const;",
        "/**",
        " * Scales a vector.",
        " * @param value Input vector.",
        " * @param factor Scale amount.",
        " * @returns The scaled vector.",
        " * @deprecated Use transform instead.",
        " */",
        "export function scale(value: Vec2, factor: number = DEFAULT_SCALE): Vec2 {",
        "  return { x: value.x * factor, y: value.y * factor };",
        "}",
        "export function setMode(mode: Mode): Mode { return mode; }",
        "export function acceptUnknown(value: unknown): unknown { return value; }",
        "export function visit(values: number[], callback: (value: number) => boolean): boolean {",
        "  return callback(values[0]);",
        "}",
        "export const CONFIG: { label: string; enabled?: boolean } = { label: \"test\" };",
        "export function convert(value: string): number;",
        "export function convert(value: number): string;",
        "export function convert(value: string | number): string | number { return String(value); }",
        "export function pair(value: number): LuaMultiReturn<[number, string]> {",
        "  return $multi(value, String(value));",
        "}",
        "function privateHelper(): void {}",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      mainPath,
      [
        'export { CONFIG, DEFAULT_SCALE, acceptUnknown, convert, pair, scale, setMode, visit } from "./math";',
        "const TIC = () => {};",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const resource = getTypeScriptResource(resources, "main");
      const declarationPath = getTypeScriptLuaDeclarationsPath(projectDir);
      const declarations = fs.readFileSync(declarationPath, "utf-8");

      expect(declarations.startsWith("---@meta _\n-- Generated by ticbuild. Do not edit.\n")).toBe(true);
      expect(declarations).toContain("---@class ticbuild.math.Vec2");
      expect(declarations).toContain("---@field x number Horizontal coordinate.");
      expect(declarations).toContain('---@alias ticbuild.math.Mode "fast"|"safe"');
      expect(declarations).toContain("---@type 2\nDEFAULT_SCALE = nil");
      expect(declarations).toContain("--- Scales a vector.");
      expect(declarations).toContain("---@deprecated Use transform instead.");
      expect(declarations).toContain("---@param value ticbuild.math.Vec2 Input vector.");
      expect(declarations).toContain("---@param factor? number Scale amount.");
      expect(declarations).toContain("---@return ticbuild.math.Vec2 # The scaled vector.");
      expect(declarations).toContain("function scale(value, factor) end");
      expect(declarations).toContain("---@param value any\n---@return any\nfunction acceptUnknown(value) end");
      expect(declarations).toContain("---@param values number[]");
      expect(declarations).toContain("---@param callback fun(value: number): boolean");
      expect(declarations).toContain("function visit(values, callback) end");
      expect(declarations).toContain("---@type { label: string, enabled?: boolean }\nCONFIG = nil");
      expect(declarations).toContain("---@overload fun(value: number): string");
      expect(declarations).toContain("function convert(value) end");
      expect(declarations).toContain("---@return number\n---@return string\nfunction pair(value) end");
      expect(declarations).toContain("function TIC() end");
      expect(declarations).toContain(`---@source ${pathToFileURL(mathPath).href}:16:1`);
      expect(declarations).not.toContain("privateHelper");
      expect(parseLua(declarations)).not.toBeNull();
      expect(resource.getCodeArtifacts(project).inputSource).not.toContain("---@meta");
      expect(resource.getDependencyList().map((dependency) => dependency.path)).not.toContain(declarationPath);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("emits Lua declarations only for reachable manifest TypeScript resources", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-lua-definitions-all-"));
    fs.writeFileSync(path.join(projectDir, "left.ts"), "export function fromLeft(value: number): number { return value; }\n", "utf-8");
    fs.writeFileSync(path.join(projectDir, "right.ts"), "this is not valid TypeScript @", "utf-8");
    const project = createProject(projectDir, [
      { name: "left", path: "left.ts", kind: "TypeScriptCode" },
      { name: "right", path: "right.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const declarations = fs.readFileSync(getTypeScriptLuaDeclarationsPath(projectDir), "utf-8");
      expect(declarations).toContain("function fromLeft(value) end");
      expect(resources.items.has("right")).toBe(false);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("imports a manifest TypeScriptCode asset by name on the first build", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-manifest-module-"));
    const mainPath = path.join(projectDir, "main.ts");
    const helpersPath = path.join(projectDir, "helpers.ts");
    fs.writeFileSync(
      helpersPath,
      [
        "/** Options accepted by Inc. */",
        "export interface IncOptions { amount: number; }",
        "/** Increments a value. */",
        "export function Inc(value: number, options: IncOptions): number {",
        "  return value + options.amount;",
        "}",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      mainPath,
      [
        'import { Inc, type IncOptions } from "ticbuild-assets/helpers";',
        "const options: IncOptions = { amount: 2 };",
        "export function TIC(): void { print(Inc(3, options)); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "helpers", path: "helpers.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const main = getTypeScriptResource(resources, "main");
      const artifacts = main.getCodeArtifacts(project);
      const declarations = fs.readFileSync(getTypeScriptManifestDeclarationsPath(projectDir), "utf-8");

      expect(declarations).toContain('declare module "ticbuild-assets/helpers"');
      expect(declarations).toContain("export interface IncOptions");
      expect(declarations).toContain("export function Inc(value: number, options: IncOptions): number;");
      expect(artifacts.inputSource).toContain('--#include "import:helpers"');
      expect(artifacts.inputSource).not.toContain("require(");
      expect(artifacts.preprocessedSource).toContain("function Inc(");
      expect(artifacts.preprocessedSource).toContain("function TIC(");
      expect(artifacts.preprocessedSource.match(/function Inc\(/g)).toHaveLength(1);
      expect(main.getDependencyList().map((dependency) => dependency.path)).toContain(helpersPath);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("typechecks manifest TypeScript imports against generated declarations on the first build", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-manifest-typecheck-"));
    fs.writeFileSync(
      path.join(projectDir, "helpers.ts"),
      "export function NumericOnly(value: number): number { return value; }\n",
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { NumericOnly } from "ticbuild-assets/helpers";',
        'export function TIC(): void { print(NumericOnly("wrong")); }',
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "helpers", path: "helpers.ts", kind: "TypeScriptCode" },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(
        /main\.ts:2:\d+ - Argument of type 'string' is not assignable to parameter of type 'number'/,
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("orders transitive manifest TypeScript modules and preserves referenced exported types", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-manifest-transitive-"));
    fs.writeFileSync(
      path.join(projectDir, "base.ts"),
      [
        "export interface AddOptions { amount: number; }",
        "export function Add(value: number, options: AddOptions): number { return value + options.amount; }",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "helpers.ts"),
      [
        'import { Add, type AddOptions } from "ticbuild-assets/base";',
        "export function AddTwice(value: number, options: AddOptions): number {",
        "  return Add(Add(value, options), options);",
        "}",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { AddTwice } from "ticbuild-assets/helpers";',
        "export function TIC(): void { print(AddTwice(1, { amount: 2 })); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "helpers", path: "helpers.ts", kind: "TypeScriptCode" },
      { name: "base", path: "base.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const artifacts = getTypeScriptResource(resources, "main").getCodeArtifacts(project);
      const declarations = fs.readFileSync(getTypeScriptManifestDeclarationsPath(projectDir), "utf-8");

      expect(declarations).toContain('declare module "ticbuild-assets/base"');
      expect(declarations).toContain('declare module "ticbuild-assets/helpers"');
      expect(declarations).toContain('from "ticbuild-assets/base"');
      expect(artifacts.preprocessedSource.match(/function Add\(/g)).toHaveLength(1);
      expect(artifacts.preprocessedSource.match(/function AddTwice\(/g)).toHaveLength(1);
      expect(artifacts.preprocessedSource.indexOf("function Add(")).toBeLessThan(
        artifacts.preprocessedSource.indexOf("function AddTwice("),
      );
      expect(artifacts.preprocessedSource.indexOf("function AddTwice(")).toBeLessThan(
        artifacts.preprocessedSource.indexOf("function TIC("),
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("preserves relative declaration dependencies behind a manifest TypeScript module", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-manifest-relative-types-"));
    fs.mkdirSync(path.join(projectDir, "helpers"));
    fs.writeFileSync(
      path.join(projectDir, "helpers", "model.ts"),
      "export interface Adjustment { amount: number; }\n",
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "helpers", "index.ts"),
      [
        'import type { Adjustment } from "./model";',
        "export function Adjust(value: number, adjustment: Adjustment): number {",
        "  return value + adjustment.amount;",
        "}",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { Adjust } from "ticbuild-assets/helpers";',
        "export function TIC(): void { print(Adjust(1, { amount: 3 })); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "helpers", path: "helpers/index.ts", kind: "TypeScriptCode" },
    ]);

    try {
      await loadAllImports(project);
      const declarations = fs.readFileSync(getTypeScriptManifestDeclarationsPath(projectDir), "utf-8");

      expect(declarations).toContain('declare module "ticbuild-assets/helpers"');
      expect(declarations).toContain('declare module "ticbuild-assets/helpers/__types/helpers/model"');
      expect(declarations).toContain('from "ticbuild-assets/helpers/__types/helpers/model"');
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("does not include a manifest TypeScript module for a type-only import", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-manifest-type-only-"));
    fs.writeFileSync(
      path.join(projectDir, "types.ts"),
      [
        "export interface Config { color: number; }",
        'export const TypeRuntimeMarker = "type-runtime-marker";',
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import type { Config } from "ticbuild-assets/types";',
        "const config: Config = { color: 3 };",
        "export function TIC(): void { cls(config.color); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "types", path: "types.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const artifacts = getTypeScriptResource(resources, "main").getCodeArtifacts(project);

      expect(artifacts.inputSource).not.toContain("import:types");
      expect(artifacts.preprocessedSource).not.toContain("type-runtime-marker");
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("imports a command-backed manifest TypeScript module", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-manifest-command-"));
    const generatedPath = path.join(projectDir, "generated", "helpers.ts");
    const generatedSource = "export function GeneratedInc(value: number): number { return value + 1; }\n";
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { GeneratedInc } from "ticbuild-assets/generatedHelpers";',
        "export function TIC(): void { print(GeneratedInc(4)); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      {
        name: "generatedHelpers",
        kind: "TypeScriptCode",
        command: {
          executable: process.execPath,
          args: [
            "-e",
            'require("fs").writeFileSync(process.argv[1], process.argv[2])',
            "generated/helpers.ts",
            generatedSource,
          ],
          outputFile: "generated/helpers.ts",
        },
      },
    ]);

    try {
      const resources = await loadAllImports(project);
      const main = getTypeScriptResource(resources, "main");
      const artifacts = main.getCodeArtifacts(project);

      expect(fs.readFileSync(generatedPath, "utf-8")).toBe(generatedSource);
      expect(artifacts.preprocessedSource).toContain("function GeneratedInc(");
      expect(main.getDependencyList().map((dependency) => dependency.path)).not.toContain(generatedPath);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("rejects cycles between manifest TypeScript modules", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-manifest-cycle-"));
    fs.writeFileSync(
      path.join(projectDir, "left.ts"),
      'import { right } from "ticbuild-assets/right"; export function left(): number { return right(); }\n',
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "right.ts"),
      'import { left } from "ticbuild-assets/left"; export function right(): number { return left(); }\n',
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "left", path: "left.ts", kind: "TypeScriptCode" },
      { name: "right", path: "right.ts", kind: "TypeScriptCode" },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(
        "TypeScript manifest module cycles are not supported: left -> right -> left",
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("rejects duplicate Lua globals across reachable manifest TypeScript resources", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-manifest-global-collision-"));
    fs.writeFileSync(
      path.join(projectDir, "left.ts"),
      'import "ticbuild-assets/right"; export const SharedGlobal = 1;\n',
      "utf-8",
    );
    fs.writeFileSync(path.join(projectDir, "right.ts"), "export const SharedGlobal = 2;\n", "utf-8");
    const project = createProject(projectDir, [
      { name: "left", path: "left.ts", kind: "TypeScriptCode" },
      { name: "right", path: "right.ts", kind: "TypeScriptCode" },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(
        "manifest code asset 'right' and left.ts both declare Lua global 'SharedGlobal'",
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("statically links imported TypeScript, preserves preprocessing, and exposes TIC callbacks", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-"));
    const mainPath = path.join(projectDir, "main.ts");
    const helperPath = path.join(projectDir, "helper.ts");
    fs.writeFileSync(
      helperPath,
      [
        "export const helper = {",
        '  suffix: " helper",',
        "  getSuffix() { return this.suffix; },",
        "};",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      mainPath,
      [
        'import { helper } from "./helper";',
        "const TIC = () => {",
        "  //#ifdef FEATURE",
        '  print(__EXPAND("$(project.name)") + helper.getSuffix());',
        "  //#else",
        '  print("disabled");',
        "  //#endif",
        "};",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(
      projectDir,
      [{ name: "main", path: "main.ts", kind: "TypeScriptCode" }],
      { FEATURE: true },
    );

    try {
      const resources = await loadAllImports(project);
      const resource = getTypeScriptResource(resources, "main");
      const artifacts = resource.getCodeArtifacts(project);

      expect(artifacts.inputSource).toContain('helper = {');
      expect(artifacts.inputSource).toContain("helper:getSuffix()");
      expect(artifacts.inputSource.indexOf('helper = {')).toBeLessThan(
        artifacts.inputSource.indexOf("TIC = function"),
      );
      expect(artifacts.inputSource).not.toContain("require(");
      expect(artifacts.inputSource).not.toContain("____modules");
      expect(artifacts.inputSource).not.toContain("____exports");
      expect(artifacts.preprocessedSource).toContain('"typescript-test"');
      expect(artifacts.preprocessedSource).not.toContain('"disabled"');
      expect(artifacts.preprocessedSource).toContain("TIC = function");
      expect(artifacts.preprocessedSource).not.toContain("_G[");
      const helperLocation = mapPreprocessedOffsetToLineColumn(
        artifacts.preprocessedSourceMap,
        artifacts.preprocessedSource.indexOf('" helper"'),
        "right",
      );
      expect(helperLocation?.file).toBe(helperPath);
      expect(helperLocation?.line).toBe(2);

      const expandedLocation = mapPreprocessedOffsetToLineColumn(
        artifacts.preprocessedSourceMap,
        artifacts.preprocessedSource.indexOf('"typescript-test"'),
        "right",
      );
      expect(expandedLocation?.file).toBe(mainPath);
      expect(expandedLocation?.line).toBe(4);
      expect(artifacts.minifiedSourceMap.segments.map((segment) => segment.originalName)).toContain("helper");
      expect(resource.getDependencyList()).toEqual(
        expect.arrayContaining([
          { path: mainPath, reason: "Imported TypeScript code file" },
          { path: helperPath, reason: "TypeScript compiler dependency" },
        ]),
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("maps a traceable generated operator line to the authored TypeScript expression", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-traceable-"));
    const mainPath = path.join(projectDir, "main.ts");
    fs.writeFileSync(
      mainPath,
      [
        "export function TIC(): void {",
        "  const lut = [1, 2, 3];",
        "  const x = lut[8];",
        "  poke(x + 1, 42);",
        "}",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(
      projectDir,
      [{ name: "main", path: "main.ts", kind: "TypeScriptCode" }],
    );
    project.manifest.assembly.lua = {
      minify: true,
      minification: { lineBehavior: "traceable" },
    };

    try {
      const resources = await loadAllImports(project);
      const artifacts = getTypeScriptResource(resources, "main").getCodeArtifacts(project);
      const operatorOffset = artifacts.minifiedSource.indexOf("\n+\n") + 1;
      const mapped = mapPreprocessedOffsetToLineColumn(
        artifacts.minifiedSourceMap,
        operatorOffset,
        "right",
      );

      expect(operatorOffset).toBeGreaterThan(0);
      expect(artifacts.minifiedSource.slice(operatorOffset, operatorOffset + 1)).toBe("+");
      expect(mapped).toMatchObject({ file: mainPath, line: 4, column: 7 });
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("uses exports as direct globals while keeping non-exported module state local", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-static-scope-"));
    fs.writeFileSync(
      path.join(projectDir, "math.ts"),
      [
        "const privateScale = 2;",
        "export function scale(value: number): number { return value * privateScale; }",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { scale as importedScale } from "./math";',
        "export function TIC(): void { print(importedScale(3)); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const artifacts = getTypeScriptResource(resources, "main").getCodeArtifacts(project);
      expect(artifacts.inputSource).toContain("local privateScale = 2");
      expect(artifacts.inputSource).toContain("function scale(value)");
      expect(artifacts.inputSource).toContain("print(scale(3))");
      expect(artifacts.inputSource).not.toContain("importedScale");
      expect(artifacts.inputSource).not.toContain("local function scale");
      expect(artifacts.inputSource.match(/^do$/gm)).toHaveLength(2);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("emits shared dependencies once in deterministic dependency-first order", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-diamond-"));
    fs.writeFileSync(path.join(projectDir, "shared.ts"), 'export const sharedMarker = "shared once";\n', "utf-8");
    fs.writeFileSync(
      path.join(projectDir, "left.ts"),
      ['import { sharedMarker } from "./shared";', "export const left = sharedMarker + \" left\";"].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "right.ts"),
      ['import { sharedMarker } from "./shared";', "export const right = sharedMarker + \" right\";"].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { left } from "./left";',
        'import { right } from "./right";',
        "export function TIC(): void { print(left + right); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const source = getTypeScriptResource(resources, "main").getCodeArtifacts(project).inputSource;
      expect(source.match(/sharedMarker = "shared once"/g)).toHaveLength(1);
      expect(source.indexOf('sharedMarker = "shared once"')).toBeLessThan(source.indexOf("left ="));
      expect(source.indexOf('sharedMarker = "shared once"')).toBeLessThan(source.indexOf("right ="));
      expect(source.indexOf("left =")).toBeLessThan(source.indexOf("function TIC()"));
      expect(source.indexOf("right =")).toBeLessThan(source.indexOf("function TIC()"));
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("treats relative declaration modules as typed Lua global contracts", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-lua-contract-"));
    fs.writeFileSync(
      path.join(projectDir, "lua-env.d.ts"),
      "export declare function LuaFract(value: number): number;\n",
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { LuaFract as fract } from "./lua-env";',
        "export function callLua(value: number): number { return fract(value); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const artifacts = getTypeScriptResource(resources, "main").getCodeArtifacts(project);
      expect(artifacts.inputSource).toContain("return LuaFract(value)");
      expect(artifacts.inputSource).not.toContain("require(");
      expect(artifacts.inputSource).not.toContain("lua-env");
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("links named re-exports without a runtime module object", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-reexport-"));
    fs.writeFileSync(
      path.join(projectDir, "base.ts"),
      "export function utility(): number { return 4; }\n",
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "barrel.ts"),
      'export { utility as renamedUtility } from "./base";\n',
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { renamedUtility } from "./barrel";',
        "export function TIC(): void { print(renamedUtility()); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const source = getTypeScriptResource(resources, "main").getCodeArtifacts(project).inputSource;
      expect(source).toContain("function utility()");
      expect(source).toContain("renamedUtility = utility");
      expect(source).toContain("print(renamedUtility())");
      expect(source).not.toContain("require(");
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("keeps TypeScriptToLua helpers self-contained without runtime module loading", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-class-link-"));
    fs.writeFileSync(
      path.join(projectDir, "counter.ts"),
      [
        "export class Counter {",
        "  public value = 0;",
        "  public increment(): void { this.value++; }",
        "}",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { Counter } from "./counter";',
        "const counter = new Counter();",
        "export function TIC(): void { counter.increment(); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const source = getTypeScriptResource(resources, "main").getCodeArtifacts(project).inputSource;
      expect(source).toContain("Counter = __TS__Class()");
      expect(source).toContain("__TS__New(Counter)");
      expect(source).not.toContain("require(");
      expect(source).not.toContain("lualib_bundle");
      expect(source).not.toContain("____modules");
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("rejects duplicate global exports before emitting ambiguous Lua", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-duplicate-export-"));
    fs.writeFileSync(path.join(projectDir, "left.ts"), "export function collide(): number { return 1; }\n", "utf-8");
    fs.writeFileSync(path.join(projectDir, "right.ts"), "export function collide(): number { return 2; }\n", "utf-8");
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      ['import "./left";', 'import "./right";', "export function TIC(): void {}"].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(
        /exported Lua global 'collide'.*left\.ts.*right\.ts/,
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("rejects static module cycles with the cycle path", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-cycle-"));
    fs.writeFileSync(
      path.join(projectDir, "a.ts"),
      ['import { b } from "./b";', "export function a(): number { return b(); }"].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "b.ts"),
      ['import { a } from "./a";', "export function b(): number { return a(); }"].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      ['import { a } from "./a";', "export function TIC(): void { print(a()); }"].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(/module cycles.*a\.ts -> b\.ts -> a\.ts/);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it.each([
    ['import value from "./dep"; export function TIC() { print(value); }', "default imports"],
    ['import * as dep from "./dep"; export function TIC() { print(dep.value); }', "namespace imports"],
    ['export * from "./dep";', "export *"],
    ['export async function load() { return import("./dep"); }', "dynamic import()"],
  ])("rejects unsupported static module syntax: %s", async (mainSource, expectedMessage) => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-module-syntax-"));
    fs.writeFileSync(path.join(projectDir, "dep.ts"), "const value = 1; export { value as default, value };\n", "utf-8");
    fs.writeFileSync(path.join(projectDir, "main.ts"), `${mainSource}\n`, "utf-8");
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(expectedMessage);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("lets direct TypeScript globals participate in Lua global renaming", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-global-minify-"));
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        "//#minify allow_rename",
        "export function VeryLongTypeScriptFunction(): number { return 7; }",
        "export function TIC(): void { print(VeryLongTypeScriptFunction()); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const resource = getTypeScriptResource(resources, "main");
      const artifacts = resource.getCodeArtifacts(project);
      expect(resource.getPreprocessResult().minifyAllowedGlobalNames).toContain("VeryLongTypeScriptFunction");
      expect(artifacts.preprocessedSource).toContain("function VeryLongTypeScriptFunction()");
      expect(artifacts.minifiedSource).not.toContain("VeryLongTypeScriptFunction");
      expect(artifacts.minifiedSourceMap.segments.map((segment) => segment.originalName)).toContain(
        "VeryLongTypeScriptFunction",
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("lets TypeScript globals opt out of automatic Lua global renaming", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-global-no-rename-"));
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        "//#minify no_rename",
        "export function PublicTypeScriptApi(): number { return InternalTypeScriptHelper(); }",
        "export function InternalTypeScriptHelper(): number { return 7; }",
        "export function TIC(): void { print(PublicTypeScriptApi()); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);
    project.manifest.assembly.lua = {
      minify: true,
      minification: { globalSymbolRenaming: "opt-out" },
    };

    try {
      const resources = await loadAllImports(project);
      const resource = getTypeScriptResource(resources, "main");
      const artifacts = resource.getCodeArtifacts(project);
      expect(resource.getPreprocessResult().minifyGlobalNamesToKeep).toContain("PublicTypeScriptApi");
      expect(artifacts.minifiedSource).toContain("function PublicTypeScriptApi()");
      expect(artifacts.minifiedSource).not.toContain("InternalTypeScriptHelper");
      expect(artifacts.minifiedSource).toContain("function TIC()");
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("resolves relative Lua includes from the TypeScript module that authored the directive", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-relative-include-"));
    const featureDir = path.join(projectDir, "feature");
    fs.mkdirSync(featureDir);
    const mainPath = path.join(projectDir, "main.ts");
    const helperPath = path.join(featureDir, "helper.ts");
    const localLuaPath = path.join(featureDir, "local.lua");
    fs.writeFileSync(
      mainPath,
      ['import "./feature/helper";', "export function TIC(): void { cls(0); }"].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      helperPath,
      ['//--#include "./local.lua"', 'export const helper = "loaded";'].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(localLuaPath, 'trace("nested Lua include")\n', "utf-8");
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const artifacts = getTypeScriptResource(resources, "main").getCodeArtifacts(project);
      const includedOffset = artifacts.preprocessedSource.indexOf('trace("nested Lua include")');
      expect(includedOffset).toBeGreaterThanOrEqual(0);
      const includedLocation = mapPreprocessedOffsetToLineColumn(
        artifacts.preprocessedSourceMap,
        includedOffset,
        "right",
      );
      expect(includedLocation).toMatchObject({ file: localLuaPath, line: 1, column: 0 });
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("distinguishes source files with the same basename", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-duplicate-basename-"));
    const leftDir = path.join(projectDir, "left");
    const rightDir = path.join(projectDir, "right");
    fs.mkdirSync(leftDir);
    fs.mkdirSync(rightDir);
    const mainPath = path.join(projectDir, "main.ts");
    const leftPath = path.join(leftDir, "shared.ts");
    const rightPath = path.join(rightDir, "shared.ts");
    fs.writeFileSync(leftPath, 'export const left = "left source";\n', "utf-8");
    fs.writeFileSync(rightPath, 'export const right = "right source";\n', "utf-8");
    fs.writeFileSync(
      mainPath,
      [
        'import { left } from "./left/shared";',
        'import { right } from "./right/shared";',
        "export function TIC(): void { print(left + right); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const artifacts = getTypeScriptResource(resources, "main").getCodeArtifacts(project);
      const leftLocation = mapPreprocessedOffsetToLineColumn(
        artifacts.preprocessedSourceMap,
        artifacts.preprocessedSource.indexOf('"left source"'),
        "right",
      );
      const rightLocation = mapPreprocessedOffsetToLineColumn(
        artifacts.preprocessedSourceMap,
        artifacts.preprocessedSource.indexOf('"right source"'),
        "right",
      );
      expect(leftLocation?.file).toBe(leftPath);
      expect(rightLocation?.file).toBe(rightPath);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("emits an exported TIC callback directly as a Lua global", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-exported-tic-"));
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      "export function TIC(): void { cls(0); }\n",
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const resource = getTypeScriptResource(resources, "main");
      const artifacts = resource.getCodeArtifacts(project);

      expect(artifacts.inputSource).toContain("function TIC()");
      expect(artifacts.inputSource).not.toContain("____exports");
      expect(artifacts.inputSource).not.toContain("____entry");
      expect(artifacts.inputSource).not.toContain("_G[");
      expect(artifacts.inputSource).not.toContain("__TICBUILD_EXPORT_GLOBAL__");
      expect(artifacts.preprocessedSource).not.toContain("__TICBUILD_EXPORT_GLOBAL__");
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("lets generated TypeScript Lua include a Lua code asset", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-lua-include-"));
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        "declare const fromLua: string;",
        '//--#include "import:luaHelper"',
        "const TIC = () => print(fromLua);",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(path.join(projectDir, "helper.lua"), 'local fromLua = "included"\n', "utf-8");
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "luaHelper", path: "helper.lua", kind: "LuaCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const resource = getTypeScriptResource(resources, "main");
      expect(resource.getPreprocessResult().code).toContain('local fromLua = "included"');
      expect(resource.getDependencyList().map((dependency) => dependency.path)).toContain(
        path.join(projectDir, "helper.lua"),
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("imports a manifest LuaCode asset as a typed TypeScript module", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-lua-module-"));
    const mainPath = path.join(projectDir, "main.ts");
    const luaPath = path.join(projectDir, "luaUtils.lua");
    fs.writeFileSync(
      luaPath,
      [
        "--- Clamps a number to the supplied range.",
        "---@param value number",
        "---@param minimum integer",
        "---@param maximum number",
        "---@return number",
        "function Clamp(value, minimum, maximum)",
        "  return math.min(math.max(value, minimum), maximum)",
        "end",
        "LuaVersion = \"one\"",
        "local function HiddenHelper() end",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      mainPath,
      [
        'import { Clamp as clampFromLua, LuaVersion } from "ticbuild-assets/LuaUtils";',
        "export function TIC(): void {",
        "  print(clampFromLua(12, 0, 10));",
        "  print(LuaVersion);",
        "}",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "LuaUtils", path: "luaUtils.lua", kind: "LuaCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const resource = getTypeScriptResource(resources, "main");
      const artifacts = resource.getCodeArtifacts(project);
      const declarationsPath = getLuaAssetDeclarationsPath(projectDir);
      const declarations = fs.readFileSync(declarationsPath, "utf-8");

      expect(declarations).toContain('declare module "ticbuild-assets/LuaUtils"');
      expect(declarations).toContain(
        "export function Clamp(value: number, minimum: number, maximum: number): number;",
      );
      expect(declarations).toContain("export const LuaVersion: string;");
      expect(declarations).not.toContain("HiddenHelper");
      expect(artifacts.inputSource.match(/--#include "import:LuaUtils"/g)).toHaveLength(1);
      expect(artifacts.inputSource).not.toContain("require(");
      expect(artifacts.inputSource).not.toContain("clampFromLua");
      expect(artifacts.preprocessedSource).toContain("function Clamp(value, minimum, maximum)");
      expect(artifacts.preprocessedSource).toContain("print(Clamp(12, 0, 10))");
      expect(artifacts.preprocessedSource.indexOf("function Clamp")).toBeLessThan(
        artifacts.preprocessedSource.indexOf("function TIC"),
      );
      expect(resource.getDependencyList()).toEqual(
        expect.arrayContaining([{ path: luaPath, reason: "Lua preprocessor dependency" }]),
      );
      expect(resource.getDependencyList().map((dependency) => dependency.path)).not.toContain(declarationsPath);
      const luaLocation = mapPreprocessedOffsetToLineColumn(
        artifacts.preprocessedSourceMap,
        artifacts.preprocessedSource.indexOf("function Clamp"),
        "right",
      );
      expect(luaLocation?.file).toBe(luaPath);
      expect(luaLocation?.line).toBe(6);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("includes a side-effect Lua asset once across multiple TypeScript modules", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-lua-module-once-"));
    fs.writeFileSync(path.join(projectDir, "hooks.lua"), "function InstallHooks() end\n", "utf-8");
    fs.writeFileSync(
      path.join(projectDir, "helper.ts"),
      ['import "ticbuild-assets/Hooks";', "export const helper = 1;"].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import "ticbuild-assets/Hooks";',
        'import { helper } from "./helper";',
        "export function TIC(): void { print(helper); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "Hooks", path: "hooks.lua", kind: "LuaCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const artifacts = getTypeScriptResource(resources, "main").getCodeArtifacts(project);
      expect(artifacts.inputSource.match(/--#include "import:Hooks"/g)).toHaveLength(1);
      expect(artifacts.preprocessedSource.match(/function InstallHooks/g)).toHaveLength(1);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("typechecks TypeScript calls against generated LuaDoc signatures on the first build", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-lua-module-types-"));
    fs.writeFileSync(
      path.join(projectDir, "math.lua"),
      ["---@param value number", "function Double(value)", "  return value * 2", "end"].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { Double } from "ticbuild-assets/Math";',
        'export function TIC(): void { print(Double("wrong")); }',
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "Math", path: "math.lua", kind: "LuaCode" },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(
        /main\.ts:2:\d+ - Argument of type 'string' is not assignable to parameter of type 'number'/,
      );
      expect(fs.existsSync(getLuaAssetDeclarationsPath(projectDir))).toBe(true);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("rejects first-class imports which do not name a manifest code asset", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-lua-module-missing-"));
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      ['import "ticbuild-assets/Missing";', "export function TIC(): void {}"].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(
        /ticbuild-assets\/Missing.*does not name a manifest LuaCode or TypeScriptCode asset/,
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("rejects colliding globals from two imported Lua assets", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-lua-module-collision-"));
    fs.writeFileSync(path.join(projectDir, "left.lua"), "function SharedLuaGlobal() end\n", "utf-8");
    fs.writeFileSync(path.join(projectDir, "right.lua"), "function SharedLuaGlobal() end\n", "utf-8");
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        'import { SharedLuaGlobal as left } from "ticbuild-assets/Left";',
        'import { SharedLuaGlobal as right } from "ticbuild-assets/Right";',
        "export function TIC(): void { left(); right(); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "Left", path: "left.lua", kind: "LuaCode" },
      { name: "Right", path: "right.lua", kind: "LuaCode" },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(
        /manifest code assets 'Left' and 'Right' both declare Lua global 'SharedLuaGlobal'/,
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("rejects directives that include a space between // and #", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-lua-include-"));
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      [
        "declare const fromLua: string;",
        '// #include "import:luaHelper"',
        "const TIC = () => print(fromLua);",
      ].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(path.join(projectDir, "helper.lua"), 'local fromLua = "included"\n', "utf-8");
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
      { name: "luaHelper", path: "helper.lua", kind: "LuaCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const resource = getTypeScriptResource(resources, "main");
      expect(resource.getPreprocessResult().code).not.toContain('local fromLua = "included"');
      expect(resource.getDependencyList().map((dependency) => dependency.path)).not.toContain(
        path.join(projectDir, "helper.lua"),
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("lets Lua include a transpiled TypeScript asset and continue afterward", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-lua-typescript-include-"));
    fs.writeFileSync(
      path.join(projectDir, "main.lua"),
      ['--#include "import:typed"', 'print("after TypeScript")'].join("\n"),
      "utf-8",
    );
    fs.writeFileSync(
      path.join(projectDir, "typed.ts"),
      "export function typescriptTick() { return 1; }\n",
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.lua", kind: "LuaCode" },
      { name: "typed", path: "typed.ts", kind: "TypeScriptCode" },
    ]);

    try {
      const resources = await loadAllImports(project);
      const resource = resources.items.get("main");
      expect(resource).toBeInstanceOf(LuaCodeResource);
      const artifacts = (resource as LuaCodeResource).getCodeArtifacts(project);
      expect(artifacts.preprocessedSource).toContain("function typescriptTick()");
      expect(artifacts.preprocessedSource).toContain('print("after TypeScript")');
      expect(artifacts.preprocessedSource).not.toContain("____entry");
      expect(artifacts.preprocessedSource).not.toContain("require(");
      expect(artifacts.minifiedSource.length).toBeGreaterThan(0);
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("reports TypeScript diagnostics with their source location", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-error-"));
    fs.writeFileSync(
      path.join(projectDir, "main.ts"),
      ['const value: number = "wrong";', "const TIC = () => print(value);"].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      { name: "main", path: "main.ts", kind: "TypeScriptCode" },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(
        /TypeScript transpilation failed:[\s\S]*main\.ts:1:7[\s\S]*not assignable to type 'number'/,
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("loads extended tsconfig paths and ambient declarations as watched dependencies", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-config-"));
    const sourceDir = path.join(projectDir, "src");
    const helperDir = path.join(sourceDir, "helpers");
    fs.mkdirSync(helperDir, { recursive: true });
    const entryPath = path.join(sourceDir, "main.ts");
    const helperPath = path.join(helperDir, "helper.ts");
    const declarationsPath = path.join(sourceDir, "globals.d.ts");
    const baseConfigPath = path.join(projectDir, "tsconfig.base.json");
    const configPath = path.join(projectDir, "tsconfig.json");
    fs.writeFileSync(
      baseConfigPath,
      JSON.stringify({
        compilerOptions: {
          baseUrl: ".",
          paths: { "@helpers/*": ["src/helpers/*"] },
          strict: true,
          types: [],
        },
      }),
      "utf-8",
    );
    fs.writeFileSync(
      configPath,
      JSON.stringify({ extends: "./tsconfig.base.json", include: ["src/**/*.d.ts"] }),
      "utf-8",
    );
    fs.writeFileSync(declarationsPath, "declare const PROJECT_LABEL: string;\n", "utf-8");
    fs.writeFileSync(helperPath, 'export const helper = "configured";\n', "utf-8");
    fs.writeFileSync(
      entryPath,
      [
        'import { helper } from "@helpers/helper";',
        "export function configuredTick() { print(PROJECT_LABEL + helper); }",
      ].join("\n"),
      "utf-8",
    );
    const project = createProject(projectDir, [
      {
        name: "main",
        path: "src/main.ts",
        kind: "TypeScriptCode",
        typescript: { tsconfig: "tsconfig.json" },
      },
    ]);

    try {
      const resources = await loadAllImports(project);
      const resource = getTypeScriptResource(resources, "main");
      const preprocessedSource = resource.getCodeArtifacts(project).preprocessedSource;
      expect(preprocessedSource).toContain("function configuredTick()");
      expect(preprocessedSource).toContain('helper = "configured"');
      expect(resource.getDependencyList()).toEqual(
        expect.arrayContaining([
          { path: entryPath, reason: "Imported TypeScript code file" },
          { path: helperPath, reason: "TypeScript compiler dependency" },
          { path: declarationsPath, reason: "TypeScript compiler dependency" },
          { path: configPath, reason: "TypeScript project configuration" },
          { path: baseConfigPath, reason: "TypeScript project configuration" },
        ]),
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("ignores tsconfig emission settings owned by ticbuild", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-config-owned-"));
    fs.writeFileSync(
      path.join(projectDir, "tsconfig.json"),
      JSON.stringify({
        compilerOptions: {
          target: "ES5",
          noEmit: true,
          declaration: true,
          outDir: "dist",
          types: [],
        },
        tstl: {
          luaTarget: "5.1",
          noHeader: false,
        },
      }),
      "utf-8",
    );
    fs.writeFileSync(path.join(projectDir, "main.ts"), "export function tick() {}\n", "utf-8");
    const project = createProject(projectDir, [
      {
        name: "main",
        path: "main.ts",
        kind: "TypeScriptCode",
        typescript: { tsconfig: "tsconfig.json" },
      },
    ]);
    const warningSpy = jest.spyOn(cons, "warning").mockImplementation(() => undefined);

    try {
      const resources = await loadAllImports(project);
      const source = getTypeScriptResource(resources, "main").getCodeArtifacts(project).inputSource;
      expect(source).toContain("function tick()");
      expect(source).not.toContain("TypeScriptToLua");
      expect(warningSpy).toHaveBeenCalledWith(expect.stringContaining("compilerOptions.noEmit"));
      expect(warningSpy).toHaveBeenCalledWith(expect.stringContaining("tstl.luaTarget"));
    } finally {
      warningSpy.mockRestore();
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("reports malformed tsconfig diagnostics with their source location", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-config-error-"));
    fs.writeFileSync(path.join(projectDir, "tsconfig.json"), '{ "compilerOptions": { "strict": tru } }', "utf-8");
    fs.writeFileSync(path.join(projectDir, "main.ts"), "export function tick() {}\n", "utf-8");
    const project = createProject(projectDir, [
      {
        name: "main",
        path: "main.ts",
        kind: "TypeScriptCode",
        typescript: { tsconfig: "tsconfig.json" },
      },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow(
        /TypeScript configuration failed:[\s\S]*tsconfig\.json:1:/,
      );
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("rejects tsconfig project references before transpilation", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-config-reference-"));
    fs.writeFileSync(
      path.join(projectDir, "tsconfig.json"),
      JSON.stringify({ compilerOptions: { types: [] }, references: [{ path: "./library" }] }),
      "utf-8",
    );
    fs.writeFileSync(path.join(projectDir, "main.ts"), "export function tick() {}\n", "utf-8");
    const project = createProject(projectDir, [
      {
        name: "main",
        path: "main.ts",
        kind: "TypeScriptCode",
        typescript: { tsconfig: "tsconfig.json" },
      },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow("TypeScript project references are not supported yet");
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });

  it("rejects TypeScriptToLua plugins before they can execute", async () => {
    const projectDir = fs.mkdtempSync(path.join(os.tmpdir(), "ticbuild-typescript-config-plugin-"));
    fs.writeFileSync(
      path.join(projectDir, "tsconfig.json"),
      JSON.stringify({ compilerOptions: { types: [] }, tstl: { luaPlugins: [{ name: "not-installed" }] } }),
      "utf-8",
    );
    fs.writeFileSync(path.join(projectDir, "main.ts"), "export function tick() {}\n", "utf-8");
    const project = createProject(projectDir, [
      {
        name: "main",
        path: "main.ts",
        kind: "TypeScriptCode",
        typescript: { tsconfig: "tsconfig.json" },
      },
    ]);

    try {
      await expect(loadAllImports(project)).rejects.toThrow("TypeScriptToLua plugins are not supported yet");
    } finally {
      fs.rmSync(projectDir, { recursive: true, force: true });
    }
  });
});
